- name: 'A'
  target:
        pstate: False
        c1: '2-2'
        c1e: '10-20'
        c6: True
  config:
        kernel: 
                image: '4.15.18-c1-2-2-c1e-10-20'
                grub_entry: 1
        boot_options:  
                'intel_pstate=disable'
