- name: 'baseline'
  config:
      pstate: False
      c1: '2-2'
      c1e: '10-20'
      c6: True
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:
      menuentry: '0>0'
      boot_options: 'intel_pstate=disable'
- name: 'disable-cstates'
  config:
      pstate: False
      c1: False
      c1e: False
      c6: False
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:      
      menuentry: '0>0'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=0 idle=poll'
- name: 'disable-c6'
  config:
      pstate: False
      c1: '2-2'
      c1e: '10-20'
      c6: False
  kernel: '4.15.18-c1-2-2-c1e-10-20'
  grub:      
      menuentry: '0>0'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2'
- name: 'quick-c1'
  config:
      pstate: False
      c1: '1-1'
      c1e: '10-20'
      c6: False
  kernel: '4.15.18-c1-1-1-c1e-10-20'
  grub:      
      menuentry: '0>2'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2'
- name: 'quick-c1-disable-c6'
  config:
      pstate: False
      c1: '1-1'
      c1e: '10-20'
      c6: False
  kernel: '4.15.18-c1-1-1-c1e-10-20'
  grub:      
      menuentry: '0>2'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2'
- name: 'quick-c1-c1e'
  config:
      pstate: False
      c1: '1-1'
      c1e: '5-20'
      c6: False
  kernel: '4.15.18-c1-1-1-c1e-10-20'
  grub:      
      menuentry: '0>4'
      boot_options: 'intel_pstate=disable intel_idle.max_cstate=2'
