---
- name: Install dependencies and binaries
  hosts: all
  tags: 
  - configuration
  tasks:
  - name: Install dependencies
    become: yes
    apt:
      update_cache: yes
      pkg:
      - libevent-dev 
      - libzmq3-dev
  - name: Install tools
    become: yes
    apt:
      update_cache: yes
      pkg:
      - sysstat
      - linux-tools-common
      - linux-tools-generic
      - linux-tools-5.4.0-88-generic
  - name: Copy memcached binary
    copy:
      src: ./memcached/memcached
      dest: ~/
      mode: 0700
  - name: Copy memcache-perf binary
    copy:
      src: ./memcache-perf/mcperf
      dest: ~/
      mode: 0700

- name: Kill memcached server
  hosts: server
  tags: 
  - kill_server
  tasks:
  - name: Kill memcached server       
    ignore_errors: yes
    shell: pkill memcached 

- name: Run memcached server
  hosts: server
  tags: 
  - run_server
  tasks:
  - name: Run memcached server
    command: ./memcached -t 20 -c 32768
    async: 10000 
    poll: 0

- name: Kill agents
  hosts: agents
  tags:
  - kill_agents
  tasks:
  - name: Kill agents    
    ignore_errors: yes
    shell: pkill mcperf 
 
- name: Run agents
  hosts: agents
  tags: 
  - run_agents
  tasks:
  - name: Run agent
    shell: ./mcperf -T 40 -A
    async: 10000 
    poll: 0  

- name: Check status
  hosts: 
  - agents
  - server  
  tags: 
  - status
  tasks:
  - name: Check memcached status
    shell: ps aux | grep memcached
  - name: Check agent status
    shell: ps aux | grep mcperf
