---
- name: Install dependencies and binaries
  hosts: all
  tags: 
  - configuration

  tasks:
  - name: Install dependencies
    become: yes
    apt:
      update_cache: yes
      pkg:
      - libevent-dev 
      - libzmq3-dev
      tags: 
      - configuration

  - name: Install tools
    become: yes
    apt:
      update_cache: yes
      pkg:
      - sysstat
      tags: 
      - configuration

  - name: Copy memcached binary
    copy:
      src: ./memcached/memcached
      dest: ~/
      mode: 0700
    tags: 
    - configuration

  - name: Copy memcache-perf binary
    copy:
      src: ./memcache-perf/mcperf
      dest: ~/
      mode: 0700
    tags: 
    - configuration

- name: Kill memcached server
  tasks:

  ignore_errors: yes
  shell: pkill memcached 
  tags: 
  - kill

- name: Run memcached server
  command: ./memcached -t 20 -c 32768
  async: 10000 
  poll: 0
  tags: 
  - run

- name: Kill agents
  hosts: agents
  ignore_errors: yes
  shell: pkill mcperf 
  tags: 
  - kill
 
- name: Run agents
  hosts: agents
  tags: 
  - run

  tasks:
  - name: Run agent
    shell: ./mcperf -T 40 -A
    async: 10000 
    poll: 0     

