---
- name: Configure machine
  hosts: memcached
  tasks:
  - name: Enable turbo boost
    ignore_errors: yes
    become: yes
    shell: echo 0 > /sys/devices/system/cpu/intel_pstate/no_turbo
    when: TURBO is defined and TURBO|bool==true
  - name: Disable turbo boost
    ignore_errors: yes
    become: yes
    shell: echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
    when: TURBO is defined and TURBO|bool==false
  - name: check if 'intel_idle.max_cstate=0 idle=halt' is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*intel_idle\.max_cstate=0 idle=halt\"$'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false
  - debug:
      msg: "{{ grub_cmdline_check.found }}"
  - name: insert 'intel_idle.max_cstate=0 idle=halt' if missing
    become: yes
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 intel_idle.max_cstate=0 idle=halt"'
    when: grub_cmdline_check.found == 0
    notify: 
    - update grub
    - reboot_machine

  handlers:
  - name: update grub
    become: yes
    shell: update-grub2
  - name: reboot_machine
    become: yes
    reboot:
